### ISSUE TITLE
https://github.com/awsdocs/amazon-lightsail-developer-guide/blob/master/doc_source/amazon-lightsail-add-blogs-as-domains-to-your-wordpress-multisite.md

### ISSUE THREAD

**Issue by apaves** [awsdocs/amazon-lightsail-developer-guide#19]
This page details using the WordPress MU Domain Mapping plugin

It is no pre-installed as suggested. Perhaps Wordpress has now found a solution?

Please advise. 

Thanks

**Comment by apaves** [comment]
@rlatino Can you help at all?

**Comment by rlatino** [comment]
Hi @apaves  - Researching this today and will have an answer for you by end of day. Thank you for your patience.

**Comment by rlatino** [comment]
Hi @apaves - The WordPress MU Domain Mapping plugin is still available to be installed via the plugins library from WordPress, but I don't think it has been tested with the latest version of WordPress, or it has not been updated for the latest version of WordPress, hence why it's no longer bundled with the image. I'm going to need more time to test the plugin to see if I can get it to work with the current version of WordPress Multisite that is available on Lightsail. I'll follow up soon when I have more information.

**Comment by apaves** [comment]
I can see "Domain Mapping" under settings as standard i.e. without MU Domain Mapping Installed (this is why I believe Wordpress has included it in their package). 

It says "Please copy sunrise.php to /opt/bitnami/apps/wordpress/htdocs/wp-content/sunrise.php and ensure the SUNRISE definition is in /opt/bitnami/apps/wordpress/htdocs/wp-config.php"

Does that shed light on things?

**Comment by apaves** [comment]
Hello @rlatino 

I found this: https://wordpress.org/support/article/wordpress-multisite-domain-mapping/ 

It says: "In WordPress 4.5+, domain mapping is a native feature." 

I'm a n00bie to AWS - can you guide as to how to locate sunrise.php and copy it etc?

Thanks for your help.

**Comment by apaves** [comment]
Hi @rlatino I hope you are well. 

How is progress coming along? 

Let me know 

Thanks

**Comment by rlatino** [comment]
Hi @apaves,

Sorry for the delay. I found a solution. For the most part, the instructions in [this doc](https://wordpress.org/support/article/wordpress-multisite-domain-mapping/) do work but you'll have to make a few adjustments. I will update the Lightsail docs with the new steps, but it will require a few days to go through our editorial process.

These are the basic steps:

1. Create a WordPress Multisite (WP MU) in Lightsail.
2. Define the primary domain of your WP MU site. Follow [this guide](https://lightsail.aws.amazon.com/ls/docs/en_us/articles/amazon-lightsail-define-the-primary-domain-for-your-wordpress-multisite).
3. Add blogs as subdomains to your WordPress Multisite instance in Amazon Lightsail. Follow [this guide](https://lightsail.aws.amazon.com/ls/docs/en_us/articles/amazon-lightsail-add-blogs-as-subdomains-to-your-wordpress-multisite).
4. Sign in to your WP MU, click **My Sites** > **Network Admin** > **Sites**, and click **Edit** for the site that you want to map as an apex domain. Edit the **Site Address** text box to the apex domain that you want to use, and click **Save Changes**.
5. Edit the DNS of the apex domain that you want to use. Add an A record to that domain's DNS, and point it to the public IP address of your WP MU instance.
The apex domain should now be mapped to the subsite in your WP MU instance. However, any admins who try to sign in to that subsite's dashboard will get a cookie error.
6. To resolve the cookie error, SSH into your WP instance, and run this command to open the wp-config.php file using Vim:
```sudo vim /opt/bitnami/apps/wordpress/htdocs/wp-config.php```
7. Add the following code to the wp-config file right below the ```define('WP_ALLOW_MULTISITE', true);``` line:
```define('COOKIE_DOMAIN', $_SERVER['HTTP_HOST']);``` 
8. Save your edit to the wp-config.php file (write and quit Vim), and you're done.

If you can sit tight for a few days, I will update the docs with a more clear set of steps, and publish the update. I can come back to this issue and let you know when the docs are updated.

**Comment by rlatino** [comment]
I have updated the doc with new instructions that work.

Published: [Add blogs as domains to your WordPress Multisite instance in Amazon Lightsail](https://lightsail.aws.amazon.com/ls/docs/en_us/articles/amazon-lightsail-add-blogs-as-domains-to-your-wordpress-multisite)


[View the diff](https://github.com/awsdocs/amazon-lightsail-developer-guide/commit/de5bcde3b9a379a74b5875568a27b60c913aa2a1?short_path=4350b32#diff-4350b328f30a02d21311c291e05da3d4886ef39fdc2ddc35f7a3106a98ed51a6)
