### ISSUE TITLE
About translated documents

### ISSUE THREAD

**Issue by miniesam** [awsdocs/amazon-lightsail-developer-guide#2]
I think it would be nice to have translated documents on GitHub, too.
The version of the translated document can be viewed on the Lightsail documentation page, but not in this GitHub repository.
So, I wonder if you can display the translated documents on GitHub as well.

**Comment by rlatino** [comment]
We don't add the translated documentation to GitHub because we don't currently have the resources to manage pull requests and feedback in the different languages. However, I have shared your feedback with our team in case it's something that can be considered in the future.
