### ISSUE TITLE
AWS lightsail MYSQL managed instance has no memory usage metric

### ISSUE THREAD

**Issue by Sas002** [awsdocs/amazon-lightsail-developer-guide#20]
We are using aws lightsail MYSQL managed instance and our customers are complaining about low memory error . There is no way to monitor memory usage for Linux VM instance which we use as LAMP and  MYSQL ( AWS managed ) . So are not sure if DB or APP which has memory usage issue. 

How can we monitor and get metric MYSQL managed database memory usage

**Comment by rlatino** [comment]
Hi @Sas002 ,

You can monitor many metrics for your instance within the Lightsail console. For more info, see [this Lightsail guide](https://lightsail.aws.amazon.com/ls/docs/en_us/articles/amazon-lightsail-resource-health-metrics). However, the Lightsail console doesn't offer memory utilization metric monitoring. For that, you will have to use tools from within your instance. I recommend installing ```htop``` on the instance to monitor its processes, and keep an eye on processes that have high memory utilization. We don't have documentation for using ```htop```, but there are a lot of online resources that cover the topic. 

If when using ```htop``` you find that MySQL is indeed the culprit of high memory utilization, then MySQL itself offers tools to help you diagnose what's using up memory. [This external blog post](https://severalnines.com/database-blog/what-check-if-mysql-memory-utilisation-high) offers some good information on finding the source of high memory utilization in MySQL.

If you continue experiencing issues, please [submit a ticket with AWS Support](https://console.aws.amazon.com/support/), who can provide further assistance diagnosing your issue. This Github repo is primarily for submitting feedback regarding the Lightsail docs. I have added "instance memory utilization monitoring" as a topic for future documentation within the Lightsail docs.
