### ISSUE TITLE
SSL certificate instructions missing from WordPress Quick Start Guide

### ISSUE THREAD

**Issue by michaelwlind** [awsdocs/amazon-lightsail-developer-guide#23]
I just set up my first WordPress site on Lightsail using the Quick Start Guide. I did not see any instructions on how to set up the SSL certificate for the site after step 4, mapping your domain to the site. I was able to find the [instructions in the Bitnami documentation](https://docs.bitnami.com/aws/how-to/generate-install-lets-encrypt-ssl/) and they worked great. Could you please add a link to those instructions in the Quick Start Guide? 

Thanks,
Michael

**Comment by rlatino** [comment]
Hi michaelwlind,
Thank you for the suggestion. We will add links to the documentation soon. We are also in the process of updating our SSL certificate documentation to use Bitnami's new tool. That new documentation, along with your suggested cross-linking, should be published soon after some testing.
