### ISSUE TITLE
This page looks to be obsolete RE cloudformation

### ISSUE THREAD

**Issue by lukewiwa** [awsdocs/amazon-lightsail-developer-guide#26]
`doc_source/amazon-lightsail-cloudformation-stacks.md`

Nothing comes up in the task menu when creating a new instance.

**Comment by rlatino** [comment]
Hi @lukewiwa ,

The task menu lists tasks for when you export a Lightsail instance or disk snapshot to EC2, and when you create new resources in EC2 from those exported snapshots. It does not display tasks for when you create a new instance within Lightsail.
