### ISSUE TITLE
I use AWS Lightsail server it is slowing down badly and its taking too much time to response

### ISSUE THREAD

**Issue by currentaffairsreview** [awsdocs/amazon-lightsail-developer-guide#29]
I use AWS Lightsail Server in Wordpress platform. My domain name is from Godaddy. 
Recently I am facing an issue with server, it is taking too much time to respond that's why my website **www.currentaffairsreview.com** has been slowed down badly. It is taking more than 1 minute time to load. This issue is in both interfaces user interface as well as Admin Panel.
This issue is affecting my website status. 
**Please Help Its Urgent!!!**

**Comment by rlatino** [comment]
Hi @currentaffairsreview ,

There might be a service, or plugin running on your instance that is causing it to consume more CPU. When your instance consumes more CPU, it may reach a point at which your instance performs at a lower CPU level. For more information, see [Viewing instance burst capacity in Amazon Lightsail](https://lightsail.aws.amazon.com/ls/docs/en_us/articles/amazon-lightsail-viewing-instance-burst-capacity). If you continue to experience issues, then please [contact support](https://console.aws.amazon.com/support/) through the AWS Console:
