### ISSUE TITLE
WordPress MU Domain Mapping doesnt exist

### ISSUE THREAD

**Issue by MatthiasMuller** [awsdocs/amazon-lightsail-developer-guide#31]
Im following the guide "Add blogs as domains to your WordPress Multisite instance in Amazon Lightsail" to open other sites but i cant find or add the plugin

**Comment by rlatino** [comment]
The ability to map multiple domains within a WP multisite dashboard is now native to WordPress and doesn't requrie a plugin. We are in the process of updating the documentation.

**Comment by rlatino** [comment]
I have updated the doc with new instructions that work.

Published: [Add blogs as domains to your WordPress Multisite instance in Amazon Lightsail](https://lightsail.aws.amazon.com/ls/docs/en_us/articles/amazon-lightsail-add-blogs-as-domains-to-your-wordpress-multisite)


[View the diff](https://github.com/awsdocs/amazon-lightsail-developer-guide/commit/de5bcde3b9a379a74b5875568a27b60c913aa2a1?short_path=4350b32#diff-4350b328f30a02d21311c291e05da3d4886ef39fdc2ddc35f7a3106a98ed51a6)
