### ISSUE TITLE
https://lightsail.aws.amazon.com/ls/docs/en_us/articles/amazon-lightsail-using-lets-encrypt-certificates-with-wordpress PreReq Failure

### ISSUE THREAD

**Issue by JFolberth** [awsdocs/amazon-lightsail-developer-guide#33]
When walking through: https://lightsail.aws.amazon.com/ls/docs/en_us/articles/amazon-lightsail-using-lets-encrypt-certificates-with-wordpress to setup my Wordpress site as SSL getting an error when executing the `sudo apt-get update` command.

Getting the below error output:
![image](https://user-images.githubusercontent.com/14017455/92778071-d4c73a80-f36e-11ea-9bbd-f26dd3433692.png)

On googling looks like an issue with certbot and the version of Ubuntu:
https://stackoverflow.com/questions/60249177/e-the-repository-http-ppa-launchpad-net-certbot-certbot-ubuntu-focal-release

Please provide guidance on how to proceed to correctly set this up in LightSail

**Comment by rlatino** [comment]
Hi @JFolberth ,

Can you please confirm if the distribution of your WordPress instance is Ubuntu or Debian. The WordPress instances on Lightsail were recently switched from Ubuntu to Debian. I need to know which of the two your instance is, so that I can further research. Thanks!

**Comment by JFolberth** [comment]
Looks to be Debian

**Comment by rlatino** [comment]
@JFolberth I will look into it today and report back. Thanks for the notice!

**Comment by rlatino** [comment]
@JFolberth I tested the tutorial steps on a WordPress instance running Debian and determine that you can skip steps 2.4 and 2.5 of the tutorial to avoid the error. Even if you do perform steps 2.4 and 2.5, you can continue the tutorial without any issues.

So after connecting to your instance via terminal, run the following sequence of commands:

Update the software packages on your instance:
```sudo apt-get update```

Install certbot:
```sudo apt-get install certbot -y```

Set the environment variables for your domain:
```DOMAIN=example.com```
```WILDCARD=*.$DOMAIN```

Start certbot in interactive mode.
```sudo certbot -d $DOMAIN -d $WILDCARD --manual --preferred-challenges dns certonly```

From there on the tutorial is the same. I will add a note to the doc that steps 2.4 and 2.5 are required only for WordPress instances that are still running Ubuntu (WordPress instances created in Lightsail before Aug. 3, 2020).

**Comment by JFolberth** [comment]
@rlatino Thanks that worked!
