### ISSUE TITLE
Lightsail TLS Certificate Installation - Update Method

### ISSUE THREAD

**Issue by gmicek** [awsdocs/amazon-lightsail-developer-guide#37]
Hi,

The method detailed in this doc appears to be deprecated and replaced by the following doc:
Deprecated: https://lightsail.aws.amazon.com/ls/docs/en_us/articles/amazon-lightsail-using-lets-encrypt-certificates-with-wordpress

Updated: https://aws.amazon.com/premiumsupport/knowledge-center/linux-lightsail-ssl-bitnami/

The updated doc uses a mechanism that makes it easier to auto-renew at 90 days

Thanks!
Greg

**Comment by gmicek** [comment]
cc @rlatino on this one as you appear to be the doc owner for the lightsail doc, thanks !

**Comment by DanielApt** [comment]
FYI: I just followed https://lightsail.aws.amazon.com/ls/docs/en_us/articles/amazon-lightsail-enabling-https-on-wordpress, which also uses `bncert`

**Comment by misterzero** [comment]
This documentation assumes you want to enable HTTPS on the wordpress instance, but does not address how one can update wordpress to work with a TLS cert on an upstream load balancer. I was able to do so, but wordpress is still using HTTP URLs for references to static content.

**Comment by rlatino** [comment]
@gmicek 
> cc @rlatino on this one as you appear to be the doc owner for the lightsail doc, thanks !

Thank you for the notice. As @DanielApt reported, we did publish the new process using the ```bncert``` tool here: https://lightsail.aws.amazon.com/ls/docs/en_us/articles/amazon-lightsail-enabling-https-on-wordpress

@misterzero I have added your suggestion to my backlog and will work on documenting that soon. Thank you!

**Comment by gmicek** [comment]
@rlatino do you want to add a note that the following doc is deprecated or remove it altogether ?

https://lightsail.aws.amazon.com/ls/docs/en_us/articles/amazon-lightsail-using-lets-encrypt-certificates-with-wordpress

That's what I was trying to get at

**Comment by rlatino** [comment]
The certbot process works, it just doesn't auto renew certs every 90 days. The benefit of the certbot process is that it configures a wildcard cert. If I recall correctly, the bncert tool doesn't support wildcard certs.

**Comment by gmicek** [comment]
Ah cool, good to know! Thanks
