### ISSUE TITLE
AWS Lightsail - Not able to send mail to client domain

### ISSUE THREAD

**Issue by devashishroy** [awsdocs/amazon-lightsail-developer-guide#41]
Hey,

I have setup to migrate from old server to new server via whm migration process but now the smtp port is not working and able to send the mail to client domain.

Any Resolutions?

**Comment by rlatino** [comment]
Hi - Apologies for delay. Please follow the instructions in this guide to enable email on your Lightsail instance: https://lightsail.aws.amazon.com/ls/docs/en_us/articles/amazon-lightsail-enabling-email-on-wordpress
