### ISSUE TITLE
https://aws.amazon.com/blogs/compute/deploying-a-highly-available-wordpress-site-on-amazon-lightsail-part-1-implementing-a-highly-available-lightsail-database-with-wordpress/

### ISSUE THREAD

**Issue by nicolaassmit** [awsdocs/amazon-lightsail-developer-guide#43]
lightsail wordpress instance, ssh mysql dump gives error:

mysqldump \
 -u root \
--databases bitnami_wordpress \
--single-transaction \
--order-by-primary \
-p > dump.sql

-bash: mysql: command not found
-bash: mysqldump: command not found

**Comment by rlatino** [comment]
Try adding ```sudo``` to the command:


```
sudo mysqldump
-u root
--databases bitnami_wordpress
--single-transaction
--order-by-primary
-p > dump.sql
```
