### ISSUE TITLE
https://lightsail.aws.amazon.com/ls/docs/en_us/articles/add-alias-record-for-lightsail-load-balancer

### ISSUE THREAD

**Issue by theshahulhameed** [awsdocs/amazon-lightsail-developer-guide#45]
When trying to add an 'A' record for the Lightsail Load Balancer in Route 53, getting the following error message:
`Bad request.
(InvalidChangeBatch 400: AAAARRDATAIllegalIPv6Address (Value is not a valid IPv6 address) encountered with 'https://22f2ec0f554a3ed19cd86f967a233d31-1611969460.eu-central-1.elb.amazonaws.com/'')`

**Comment by rlatino** [comment]
HI @theshahulhameed ,

Try to enable the "Alias" toggle, and then choose the following sequence of options (see screenshot):

![route-53-alias-record-for-load-balancer](https://user-images.githubusercontent.com/39803475/106533359-dcff4e00-64a6-11eb-8e9d-87fd92af0c4d.png)

**Comment by rlatino** [comment]
Hi @theshahulhameed - You should enable the **Alias** toggle and then choose the following options noted in the attached screenshot. It will let you enter the public endpoint of the Lightsail load balancer into the Endpoint field.
![route-53-alias-record-for-load-balancer](https://user-images.githubusercontent.com/39803475/106616653-a404bf00-6522-11eb-8007-f2c7b02d7d94.png)

**Comment by rlatino** [comment]
Closing ticket. No further action required here. Please re-open if you require additional information.
