### ISSUE TITLE
Importing the data into mysql in lightsail needs SUPER, SYSTEM_VARIABLES_ADMIN or SESSION_VARIABLES_ADMIN privilege ???

### ISSUE THREAD

**Issue by ijunc2** [awsdocs/amazon-lightsail-developer-guide#46]
After changing the mysql mode to 'data import mode' is available, I tried to import the data into lightsail mysql.
But system said that 
' Access denied; you need (at least one of) the SUPER, SYSTEM_VARIABLES_ADMIN or SESSION_VARIABLES_ADMIN privilege(s) for this operation'

the document I referred are below .
[https://lightsail.aws.amazon.com/ls/docs/en_us/articles/amazon-lightsail-configuring-database-data-import-mode](https://lightsail.aws.amazon.com/ls/docs/en_us/articles/amazon-lightsail-configuring-database-data-import-mode)

[_https://lightsail.aws.amazon.com/ls/docs/ko_kr/articles/amazon-lightsail-importing-data-into-your-mysql-database_](https://lightsail.aws.amazon.com/ls/docs/ko_kr/articles/amazon-lightsail-importing-data-into-your-mysql-database)

What problems?

**Comment by davidfabri** [comment]
I have the same problem. 
How can set privileges my user like SUPER, SYSTEM_VARIABLES_ADMIN or SESSION_VARIABLES_ADMIN?

**Comment by rlatino** [comment]
I am not able to reproduce your issue. After enabling data import mode, did you also make your database publicly accessible?

https://lightsail.aws.amazon.com/ls/docs/en_us/articles/amazon-lightsail-configuring-database-public-mode

**Comment by so3arbelnox** [comment]
Also have this problem. I'm not sure where I can configure this.

**Comment by rlatino** [comment]
Hi - We are unable to provide the dedicated support you require through GitHub. For further assistance, please get in touch with [AWS Support](https://aws.amazon.com/contact-us/).
