### ISSUE TITLE
Filezilla connecting to AWS Lightsail with windows server. 

### ISSUE THREAD

**Issue by everettc4** [awsdocs/amazon-lightsail-developer-guide#49]
Hi there I'm trying to connect filezilla to my lightsail instance that's running windows server so I can transfer files.

I have created a pair of keys and followed the instructions on this but no luck.
https://lightsail.aws.amazon.com/ls/docs/en_us/articles/amazon-lightsail-connecting-to-linux-unix-instance-using-sftp#connecting-to-linux-unix-instance-using-sftp-prerequisites

I guess my question is how do I confirm what my default user name is? I made the assumption  "ec2-user" Is correct. 

If that's true then its something else?? 

Thanks for any tips ...not much good having a server if you can't get data to it??

**Comment by rlatino** [comment]
The procedure you linked is for connecting FTP to a Linux instance in Lightsail. There is a separate set of steps for Windows, which we haven't yet written documentation for. I will add that to our list of upcoming docs. In the meantime, there are a few helpful resources online if you search for "ftp into windows server".
