### ISSUE TITLE
Add note to PrestaShop Quick Start Guide

### ISSUE THREAD

**Issue by gh0stface** [awsdocs/amazon-lightsail-developer-guide#52]
I cannot seem to find the markdown for PrestaShop Quick start guide (https://lightsail.aws.amazon.com/ls/docs/en_us/articles/amazon-lightsail-quick-start-guide-prestashop).

Within step 6 (configuring the SMTP) email, I would suggest placing a note there to navigate to the "Shop Parameter > Contacts and to adjust the contacts accordingly. Otherwise, email setup will always throw the following error: "Your domain example.com is not allowed in header 503-From" 503 Valid RCPT command must precede DATA"

**Comment by rlatino** [comment]
@gh0stface I've added your feedback to the Prestashop quick start guide. It should be published in our live docs soon.
