### ISSUE TITLE
How to check Lightsail Mysql DB Instance (RDS of Lightsail) Memory Metrix

### ISSUE THREAD

**Issue by rijans** [awsdocs/amazon-lightsail-developer-guide#62]
We have a production MySQL database in AWS Lightsail Database Instance. We can see metrics about CPU usage, storage, etc, but can't see any memory data. Even inside database, performance_schema DB's all tables are strangely empty! Did u guys configured these DB instances not to store any performance data?
Then how can we see/analyze memory matric?

**Comment by Paguiar735** [comment]
According to [this](https://github.com/awsdocs/amazon-lightsail-developer-guide/issues/20), AWS Lightsail doesn't offer memory utilization metric monitoring built-in.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
