### ISSUE TITLE
How can I get access with other account created

### ISSUE THREAD

**Issue by micke-paredes** [awsdocs/amazon-lightsail-developer-guide#68]
When I execute the commands to create user and give privileges what I need all be great. 
But when I put exit on mysql-cli and try to connect with the new user was created previously refuse my connection cause the access is denegate.

Someone knows how can I get access with other user created previously? or how can I fix it?

Please help!

And thanks!

![image](https://user-images.githubusercontent.com/16496872/145525732-1a14b5cc-f767-4653-84cf-8c2962c301ac.png)
![image](https://user-images.githubusercontent.com/16496872/145525882-bf53da00-cf7e-4b52-b481-2c054c459d0b.png)
![image](https://user-images.githubusercontent.com/16496872/145526038-850524aa-a76a-4d57-9f9f-2b1fefbe03d0.png)

**Comment by micke-paredes** [comment]
I forget that its happen in MySQL Lightsail

**Comment by Paguiar735** [comment]
We need a minimal reproducible example of the problem.

That's to say that we need a SQL script that performs all the steps you took to get the error: create the table, create user, grant said privileges. Then we need to see exactly what command you ran to get permission error.

That way we can rule out the possibility of it being an AWS problem.

In case this has been solved, would you mind closing this issue?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
