### ISSUE TITLE
Instructions are old or now very different and can't seem to run ctlscript.sh

### ISSUE THREAD

**Issue by Schumzy** [awsdocs/amazon-lightsail-developer-guide#70]
HI,

All the directories in this instruction do not exist in my instance.

my directories were stack/wordpress is where I found the config file. 

When I got to the stage to change from http to https I managed to make the edit to the config file, but can't restart getting a ctlscript.sh command not found error

**Comment by rlatino** [comment]
I am not sure which instructions you're referring to. If you're following the instructions for configuring Let's Encrypt, then we just updated those instructions to provide more guidance around the different versions of the Bitnami WordPress image. Please try again.
