### ISSUE TITLE
Bring AlmaLinux, Rocky Linux & CentOS Stream to Lightsail?

### ISSUE THREAD

**Issue by itsalongstory** [awsdocs/amazon-lightsail-developer-guide#73]
![image](https://user-images.githubusercontent.com/1243202/174538385-d98cd3e4-c471-417a-a100-157f2c8353ce.png)

CentOS 8 & Ubuntu 16.04 went **END OF LIFE**, may need to be removed from selection list.

AlmaLinux and Rocky Linux are available on EC2, when will we be able to install these Linux versions on Lightsail as well?

Debian 11 was released on August 14, 2021, but Lightsail doesn't support this version yet (June 20, 2022).

The OS versions on Lightsail are too old, and updates are very untimely.

**Comment by rlatino** [comment]
Hi @itsalongstory ,

Thank you for letting us know about the operating system versions at end of life, and your request for new operating systems on Lightsail. I have passed your feedback on to the Lightsail product management team for evaluation.

**Comment by itsalongstory** [comment]
https://aws.amazon.com/marketplace/reviews/reviews-list/B08KYLN2CG/review/98b1053b-f18d-45c7-a217-e6eaae80bee9

> By Yug on 05/27/2022 
> Error: Failed to download metadata for repo 'AppStream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
> 
> Not able to install any of the packages.

> By alextr98 on 06/16/2022
> Have the same issue - no URLs in mirror list

> By Andrew on 06/04/2022
> I've had this same issue now after ssh'ing the first time.


https://aws.amazon.com/marketplace/reviews/reviews-list/B08KYLN2CG/review/517383b2-0af6-4d90-80be-3856450d6efc

> By gerrard de jong on 02/20/2022 
> On my aws account we faced many isssues like unable to download packages, key refuses many time even after using right keys, and limited documentation support


There are a very large number of small production environments that need to run EL8, and this issue seems to need to be handled more efficiently.

As of January 31, 2022 the CentOS 8 mirrorlists are offline, this issue has been around for almost **6 months**, and the Lightsail team has done nothing to resolve the issue in the past 6 months.

This doesn't seem to fit with AWS' well-received reputation.

**Comment by zeeshanjamal16** [comment]
Why this issue is closed? We still don't have Alma Linux or Rocky Linux in Lightsail

**Comment by stbcoding** [comment]
I want to upvote Alma Linux for Lightsail.
Thanks!

**Comment by LoneFreeRanger** [comment]
AlmaLinux please!!!

**Comment by StrangePeanut** [comment]
I definitely want to see AlmaLinux added too. The issue was closed without being addressed at all. What’s going on? Is Lightsail an abandoned product?

@rlatino are you still around?

Related: https://github.com/awsdocs/amazon-lightsail-developer-guide/issues/74

**Comment by stbcoding** [comment]
Bumping this

**Comment by LoneFreeRanger** [comment]
indeed. I think they are ignoring this hence why this thread is marked as closed. Having seen this thread makes me start to think that lightsail is being phased out:

https://github.com/awsdocs/amazon-lightsail-developer-guide/issues/74

**Comment by itsalongstory** [comment]
Customers will not waste their time on a product that doesn't move forward.

Whether the documentation is good or not is no longer relevant.

**Comment by itsalongstory** [comment]
> Hi @itsalongstory ,
> 
> Thank you for letting us know about the operating system versions at end of life, and your request for new operating systems on Lightsail. I have passed your feedback on to the Lightsail product management team for evaluation.

Yes, it's been **320 days** since you passed the feedback to the Lightsail team and closed this issue. What has the Lightsail team done? There are still many blueprints in **EOL** status (#74) on the Lightsail dashboard.

**Comment by rlatino** [comment]
Hi @itsalongstory,

Lightsail released the new domain registration feature just last month. They are continuing to evaluate new features, and they have received the feedback you recently submitted. You will likely hear back from the team soon.

**Comment by LoneFreeRanger** [comment]
> Hi @itsalongstory,
> 
> Lightsail released the new domain registration feature just last month. They are continuing to evaluate new features, and they have received the feedback you recently submitted. You will likely hear back from the team soon.

Thank you. :)
