### ISSUE TITLE
Almost 50% of blueprints have reached the end of life

### ISSUE THREAD

**Issue by itsalongstory** [awsdocs/amazon-lightsail-developer-guide#74]
![lightsail](https://user-images.githubusercontent.com/1243202/176139285-ddbcd7fa-faca-482d-bf2f-ac4ec0352b28.jpg)

### Let's briefly compare some service providers of the same type:

|                    |  DigitalOcean   |      Vultr      |      Linode     | Amazon Lightsail |
| :----------------: | :-------------: | :-------------: | :-------------: | :--------------: |
|      Ubuntu        |      22.04      |      22.04      |      22.04      |      20.04       |
|      Debian        |       11        |       11        |        11       |       10         |
|      CentOS        |     Stream 9    |      Stream 9   |     Stream 9    |      8 @ EOL     |
|     openSUSE       |        /        |        /        |      15.4       |     15.2 @ EOL   |
|    Rocky Linux     |        8        |        8        |        8        |        /         |
|    AlmaLinux       |        /        |        8        |        9        |        /         |

**Comment by LoneFreeRanger** [comment]
done be surprised if this thread gets marked as closed

**Comment by rlatino** [comment]
Please submit your feedback using the Lightsail console feedback mechanism. I have passed your feedback along to the Lightsail team but it's better if you submit it yourself using the "Questions? Comments?" link that is listed in the bottom, right corner of the Lightsail console. Yes, I will mark this as closed because there's nothing that I can do to fix this issue. I can only resolve issues pertaining to Lightsail documentation. Thanks!

**Comment by itsalongstory** [comment]
> Please submit your feedback using the Lightsail console feedback mechanism. I have passed your feedback along to the Lightsail team but it's better if you submit it yourself using the "Questions? Comments?" link that is listed in the bottom, right corner of the Lightsail console. Yes, I will mark this as closed because there's nothing that I can do to fix this issue. I can only resolve issues pertaining to Lightsail documentation. Thanks!

You can certainly close this issue, but I'm curious if the Lightsail team still has engineers working on their product and if Lightsail will be taken offline in the near future.

**Comment by jbenguira** [comment]
Still expecting Ubuntu 22.04 to appear on lightsail ...
