### ISSUE TITLE
en_us transalation of this doc lacks AWS Region keywords

### ISSUE THREAD

**Issue by lakbychance** [awsdocs/amazon-lightsail-developer-guide#77]
Hey I was looking at [this](https://lightsail.aws.amazon.com/ls/docs/en_us/articles/understanding-ssh-in-amazon-lightsail) doc which deals with how to configure ssh keys for accessing your lightsail instances. I found out that **AWS Region** keywords are missing and the sentence becomes incorrect. I tried other language translations (Japanese, French & German) and all seem to have the **AWS Region** keyword as expected. 

*en_us* translation (English)
<img width="1090" alt="Screen Shot 2022-08-06 at 8 23 53 PM" src="https://user-images.githubusercontent.com/29139815/183254366-dc51c443-5d36-43d4-8d79-0bb4f1bbab40.png">

*de_de* translation (German)
<img width="1100" alt="Screen Shot 2022-08-06 at 8 23 40 PM" src="https://user-images.githubusercontent.com/29139815/183254371-032b71b3-2ff5-4486-9128-1c2a18e7c2da.png">

*fr_fr* translation (French)
<img width="1011" alt="Screen Shot 2022-08-06 at 8 23 24 PM" src="https://user-images.githubusercontent.com/29139815/183254375-e29a9bef-9257-449e-aac8-da52cd11c2e7.png">

*ja_jp* translation (Japanese)
<img width="1046" alt="Screen Shot 2022-08-06 at 8 23 04 PM" src="https://user-images.githubusercontent.com/29139815/183254381-58821383-8a4c-452e-8492-a8ddab9332a9.png">

P.S. - The github markdown is correct so it seems like an issue with translation. Somehow those keywords are being omitted in *en_us* version.

**Comment by rlatino** [comment]
This is now fixed. Thank you for the notice!
