### ISSUE TITLE
[export-0x1efecb61a2f80aa34d3b9218b564a64d05946290.csv](https://github.com/awsdocs/amazon-lightsail-developer-guide/files/9745686/export-0x1efecb61a2f80aa34d3b9218b564a64d05946290.csv)

### ISSUE THREAD

**Issue by kadoned** [awsdocs/amazon-lightsail-developer-guide#78]
[export-0x1efecb61a2f80aa34d3b9218b564a64d05946290.csv](https://github.com/awsdocs/amazon-lightsail-developer-guide/files/9745686/export-0x1efecb61a2f80aa34d3b9218b564a64d05946290.csv)

_Originally posted by @kadoned in https://github.com/awsdocs/amazon-lightsail-developer-guide/issues/39#issuecomment-1273202259_

**Comment by rlatino** [comment]
Closing this because it does not appear to be actionable.
