### ISSUE TITLE
Tutorial for Getting started using WordPress from your Amazon Lightsail instance is outdated.

### ISSUE THREAD

**Issue by JJJ000** [awsdocs/amazon-lightsail-developer-guide#80]
Tutorial for [Getting started using WordPress from your Amazon Lightsail instance](https://github.com/awsdocs/amazon-lightsail-developer-guide/blob/master/doc_source/getting-started-with-wordpress-and-lightsail.md) is outdated.

The steps to login to admin console should be done through access http://\{**Public IP**\}\/wp-login.php to log in to the admin console.

**Comment by Fizz-moment** [comment]
Lots of documents are updated. Some are as old as 2017.

**Comment by rlatino** [comment]
I have updated the documentation and the update should be live in a few hours.
