### ISSUE TITLE
Low single threaded lightsail performance, using old Intel CPU from 2015

### ISSUE THREAD

**Issue by diwu1989** [awsdocs/amazon-lightsail-developer-guide#81]
The lightsail instance seem to be running extremely old Intel Xeon CPU from 2015.
My instance seem to have CPU E5-2676 v3, which was released in 2015 and has poor single threaded performance compared to modern Intel CPU.

When will Lightsail be upgraded to modern CPU like the rest of EC2?

**Comment by rlatino** [comment]
Hi @diwu1989 ,

I don't have that information. This channel is for providing feedback for Lightsail documentation. To communicate directly with the Lightsail team, please submit feedback using the "Questions? Comments?" link that is in the lower left corner of the Lightsail console.

Thank you!

**Comment by rlatino** [comment]
@diwu1989 I can confirm that the Lightsail team received the feedback you just submitted. You should hear from the team soon. I'm closing this issue now. Thank you!

**Comment by StrangePeanut** [comment]
@diwu1989 any updates? What was their answer?
